### ISSUE TITLE
Make units have size

### ISSUE THREAD

**Issue by kronmillerg** [CheeseLord/warts#75]
Currently they're all just point particles.

**Comment by kronmillerg** [comment]
To be clear: we're not going to try to solve group pathfinding yet. Papers have been published on the subject. For now, this would only have 2 real effects: (1) a unit with one foot on the resource pool can gather from it, (2) it would fix that warning we always get about models being the wrong aspect ratio.

**Comment by kronmillerg** [comment]
Er... (2) is really more of a #61 sort of thing. Really this is just about (1).

**Comment by JoelO** [comment]
Unit size is given as a Distance object.
