### ISSUE TITLE
Units walk through impassible ground

### ISSUE THREAD

**Issue by CheeseLord** [CheeseLord/warts#77]
For example, moving from (150, 30) to (55, 115).

**Comment by kronmillerg** [comment]
In that case the server debug-logs:

    DEBUG    clie...acer Issuing orders to unit (9, 4): [<class 'src.shared.geometry.Coord'>(90, 30), <class 'src.shared.geometry.Coord'>(30, 30), <class 'src.shared.geometry.Coord'>(55, 115)].

so (supposedly, at least) the pathfinding is doing exactly what it's supposed to do.

I suspect that this was introduced when we added the new Coord object (see #70), but I haven't confirmed.
